name: Cargo Stable Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build_and_test:
    name: cargo stable build and test
    runs-on: ubuntu-latest
    steps:
      - name: checkout git
        uses: actions/checkout@v4
      - name: install rust toolchain
        run: rustup toolchain install stable --profile minimal
      - name: run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: install LLD
        run: sudo apt install -y lld
      - name: install bevy dependency libs
        run: sudo apt install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libasound2-dev libudev-dev
      - name: cargo build
        run: cargo build --verbose
      - name: cargo test
        run: cargo test --verbose
