name: Cargo Stable Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: cargo stable build and test
    runs-on: ubuntu-latest
    steps:
      - name: checkout git
        uses: actions/checkout@v4
      - name: install rust toolchain
        run: rustup toolchain install stable --profile minimal
      - name: gh actions cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.lock') }}
      - name: install LLD
        run: sudo apt install -y lld
      - name: install bevy dependency libs
        run: sudo apt install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libasound2-dev libudev-dev
      - name: cargo build
        run: cargo build --verbose
      - name: cargo test
        run: cargo test --verbose
