name: Cargo Stable Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: cargo stable build and test
    runs-on: ubuntu-latest
    steps:
      - name: checkout git
        uses: actions/checkout@v4
      - name: install rust toolchain
        run: rustup toolchain install stable --profile minimal
      - name: use rust cache
        uses: Swatinem/rust-cache@v2.2.1
      - name: install LLD
        run: sudo apt install -y lld
      - name: install bevy dependency libs
        run: sudo apt install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libasound2-dev libudev-dev
      - name: cargo build
        run: cargo build --verbose
      - name: cargo test
        run: cargo test --verbose
